kind: Service
apiVersion: v1
metadata:
  name: articles-quarkus
  labels:
    app: articles-quarkus
spec:
  selector:
    app: articles-quarkus
  ports:
    - port: 8080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: articles-quarkus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: articles-quarkus
        version: v1
    spec:
      containers:
      - name: articles-quarkus
        image: articles-quarkus:1
        ports:
        - containerPort: 8080
        env:
        - name: samplescreation
          valueFrom:
            configMapKeyRef:
              name: articles-config
              key: samplescreation
      restartPolicy: Always
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: articles-config
data:
  samplescreation: "true"
---