apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  databases:
    foo: zalando
  numberOfInstances: 2
  postgresql:
    version: '11'
  teamId: ACID
  users:
    foo_user: []
    zalando:
      - superuser
      - createdb
  volume:
    size: 1Gi