FROM open-liberty:microProfile2-java11

ADD liberty-opentracing-zipkintracer-1.2-sample.zip /

RUN unzip liberty-opentracing-zipkintracer-1.2-sample.zip -d /opt/ol/wlp/usr/ \
 && rm liberty-opentracing-zipkintracer-1.2-sample.zip

COPY liberty/server.xml /config/

ADD target/articles.war /config/dropins/

ADD target/jcc-11.1.4.4.jar /opt/ol/wlp/usr/shared/resources/jcc-11.1.4.4.jar