FROM node:12-alpine as BUILD
 
COPY src /usr/src/app/src
COPY public /usr/src/app/public
COPY package.json /usr/src/app/
COPY babel.config.js /usr/src/app/

WORKDIR /usr/src/app/
RUN yarn install
RUN yarn build


FROM bitnami/nginx:latest
#COPY nginx.conf /opt/bitnami/nginx/conf/nginx.conf
COPY --from=BUILD --chown=1001 /usr/src/app/dist /app