apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToDeploymentYamlFile
      description: The path to the yaml file with Deployment resource to deploy within the git source
    - name: pathToServiceYamlFile
      description: The path to the yaml file with Service resource to deploy within the git source
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
  tasks:
  - name: source-to-image
    taskRef:
      name: source-to-image
    params:
      - name: pathToDockerFile
        value: "${params.pathToDockerFile}"
      - name: pathToContext
        value: "${params.pathToContext}"
      - name: imageUrl
        value: "${params.imageUrl}"
      - name: imageTag
        value: "${params.imageTag}"
    resources:
      inputs:
        - name: git-source
          resource: git-source
  - name: deploy-to-cluster
    taskRef:
      name: deploy-via-kubectl
    runAfter:
      - source-to-image
    params:
      - name: pathToDeploymentYamlFile
        value:  "${params.pathToDeploymentYamlFile}"
      - name: pathToServiceYamlFile
        value:  "${params.pathToServiceYamlFile}"
      - name: imageUrl
        value: "${params.imageUrl}"
      - name: imageTag
        value: "${params.imageTag}"
    resources:
      inputs:
        - name: git-source
          resource: git-source